spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8      # 환경변수에서 가져옴
    username: ${DB_USER}
    password: ${DB_PW}
  jpa:
    show-sql: true      # 개발 서버니까 로그 봄
    hibernate:
      ddl-auto: update  # 데이터 날아가면 안 되니까 update
  logging:
    level:
      root: INFO
  data:
    redis:
      host: localhost # 같은 EC2 안에 있으므로 localhost
      port: 6379
      password: ${DEV_REDIS_PW} # PW에 ! 들어갔다가 에러났음\
  cloud:
    aws:
      cloudfront:
        domain: "https://dev-img.egobook.site" # 프론트가 S3 요소들에 접속하기 위한 도메인 주소
langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: gpt-4o-mini
      log-requests: true
      log-responses: true
server:
  url: https://dev.egobook.site
  servlet:
    session:
      cookie:
        secure: true # HTTPS(ALB)를 쓰면 true가 좋음

springdoc:
  swagger-ui:
    enabled: true

jwt:
  token:
    secretKey: ${JWT_SECRET_KEY_DEV}

management:
  endpoints:
    web:
      exposure:
        include: health # health만 노출
  endpoint:
    health:
      show-details: always # 상세 정보(DB 에러 내용 등) 표시 O

app:
  oauth:
    google:
      android-client-ids: ${DEV_ANDROID_CLIENT_IDS}

  auth:
    # HashingUtil(HmacSHA256 방식 Hashing)을 위한 설정값
    device-salt: ${DEV_SALT}

word:
  ai:
    base-url: ${WORD_AI_BASE_URL}

gemini:
  base-url: "https://generativelanguage.googleapis.com"
  api-key: "${GEMINI_API_KEY}"
  model: "gemini-2.0-flash"