spring:
  config:
    activate:
      on-profile: prod
      # => 해당 파일은 "prod"라는 이름을 달고 실행할 때만 작동할 것이라는 조건부 실행 설정
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
  jpa:
    show-sql: false      # 운영에선 쿼리 로그 끔 (성능/보안)
    hibernate:
      ddl-auto: validate  # 테이블 건들지 말고 검증만 하라는 설정
  logging:
    level:
      root: INFO
  data:
    redis:
      host: localhost # 같은 EC2 안에 있으므로 localhost
      port: 6379
      password: ${PROD_REDIS_PW}
  cloud:
    aws:
      cloudfront:
        domain: "https://prod-img.egobook.site" # 프론트가 S3 요소들에 접속하기 위한 도메인 주소
langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: gpt-4o-mini
      log-requests: true
      log-responses: true
      
server:
  url: https://www.egobook.site
  servlet:
    session:
      cookie:
        secure: true
        # => 브라우저가 주소가 https일 때만 쿠키를 서버로 보내도록 하는 설정
        # => HTTPS(ALB)를 쓰면 true가 좋음
        # => https가 적용된 곳에만 적용해야한다.
        
springdoc:
  swagger-ui:
    enabled: false # 운영 서버에서는 Swagger UI 비활성화

jwt:
  token:
    secretKey: ${JWT_SECRET_KEY_PROD}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never # 상세 정보 숨김 (기본값) -> {"status": "UP"} 만 나옴

app:
  oauth:
    google:
      android-client-ids: ${DEV_ANDROID_CLIENT_IDS}

  auth:
    # HashingUtil(HmacSHA256 방식 Hashing)을 위한 설정값
    device-salt: ${PROD_SALT}

word:
  ai:
    base-url: ${WORD_AI_BASE_URL}