package com.example.egobook_be.domain.user.entity;

public enum InkLogType {
    FIRST_EMOTION_DIARY,
    FIRST_LETTER_WRITE,
    FIRST_LETTER_REPLY,
    FIRST_QUESTION_ANSWER,
    FIRST_PSYCHOLOGY_VIEW,
    LEVEL_UP,
    ATTENDANCE_REWARD,
    DAILY_MISSION_REWARD,
    WEEKLY_MISSION_REWARD,
    WATCH_AD,
    WEEKLY_UNLOCK,
    LETTER_COLOR_PURCHASE
}